### ISSUE TITLE
Error when using path to an external file

### ISSUE THREAD

**Issue by stevehadley** [patriciogonzalezvivo/glslTexture#4]
Awesome work on this, it's really aiding in my learning however currently when I attempt to use an external .frag file it fails.

When assigning the source I entered C:\Users\steve\Pictures\test2.frag and it showed the error

`Report: Error 
Traceback (most recent call last): File "C:\Users\steve\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\gIsITexture-master\__init_.py", line 129, in modal if not bpy.data.texts[self.source].is_in_memory and bpy.data.texts[self.source].is_modified: KeyError: 'bpy_prop_collection[key]: key "C/Users/steve/Pictures/test2.frag" not found'
location: <unknown location>:-1 
`

C/Users/steve/Pictures/test2.frag does indeed exist, although it is entirely empty (I just create with the touch command in WSL).

Sorry if this is something silly I'm guessing it's the slashes, I tried reversing them but no luck. I am using Windows 10 and Blender 2.83.1

**Comment by stevehadley** [comment]
Sorry the above error message has some typos because I used OCR for it, the actual path is "C:\Users\steve\Pictures\test2.frag" and I've also tried "C:/Users/steve/Pictures/test2.frag"

**Comment by patriciogonzalezvivo** [comment]
Mmm... have you tried relative paths? The working path is where Blender is lunch and the project folder is ``//`` but could be different in Windows

**Comment by stevehadley** [comment]
Ah yes, using // worked!! I put it in the same directory as the .blend file an used //test2.frag, thanks for this such a silly issue, love your work it's helping me a lot.
